# Generated by Django 4.1 on 2024-03-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serializer', '0002_highscore_alter_todo_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highscore',
            name='player_name',
            field=models.CharField(max_length=20),
        ),
    ]
