# Generated by Django 4.1 on 2024-03-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TokenAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
